### ISSUE TITLE
Failing to build with 1.64.0-nightly

### ISSUE THREAD

**Issue by yamabiiko** [ChainSafe/forest#2025]
**Issue summary**
I run into the following error while building Forest using rustc 1.64.0-nightly (gentoo) and cargo 1.64.0-nightly.

**To Reproduce**
```
make install
```

**Log output**
```
   Compiling fvm_sdk v1.0.0
   Compiling fvm v1.1.0
   Compiling forest_crypto v0.6.0 (/home/yamabiko/Projects/open/forest/crypto)
error[E0599]: no method named `backtrace` found for struct `anyhow::Error` in the current scope
   --> /home/yamabiko/.cargo/registry/src/github.com-1ecc6299db9ec823/fvm-1.1.0/src/call_manager/backtrace.rs:137:28
    |
137 |             backtrace: err.backtrace().to_string(),
    |                            ^^^^^^^^^ method not found in `anyhow::Error`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `fvm` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `forest-cli v0.4.1 (/home/yamabiko/Projects/open/forest/forest/cli)`, intermediate artifacts can be found at `/home/yamabiko/Projects/open/forest/target`
make: *** [Makefile:14: install-cli] Error 101
```

**Environment (please complete the following information):**
 - OS: Gentoo with kernel: 6.0.0
 - rustc 1.64.0-nightly (gentoo)
 - master, latest commit

**Comment by lemmih** [comment]
Hmm, that looks like your version of `rustc` is too old. Is it possible for you to use the toolchain described in `rust-toolchain.toml`?

**Comment by yamabiiko** [comment]
Yes, using the version defined in `rust-toolchain.toml` works.
If anyone with Gentoo has both system-wide rust and rustup and got confused on why it doesn't work properly after changing to nightly with rustup: prepend `~/.cargo/bin` to your `$PATH`. 
If you append it will still use the system toolchain.
